name: mikes-raylib-wasm-builder
on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  build-docker:
    name: Build michaelfiber/mikes-raylib-wasm-builder docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run build script
        run: chmod +x ./docker-scripts/docker-build.sh && ./docker-scripts/docker-build.sh