name: mikes-raylib-wasm-builder
on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  build-docker:
    name: Build mikes-raylib-wasm-builder docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout michaelfiber/raylib-game-template
        uses: actions/checkout@v3
        with:
          path: michaelfiber-raylib-game-template
          repository: michaelfiber/raylib-game-template
      - name: Run build script
        run: cd michaelfiber-raylib-game-template && ls -lh