name: Nightly raylib WASM build
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  make-publish-branch:
    name: Make publish branch
    runs-on: ubuntu-latest
    steps:
      - name: Create publish branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'publish'
  build:
    name: Nightly raylib WASM build
    needs: [make-publish-branch]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make build-essential libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev python3
      - name: Checkout raylib
        uses: actions/checkout@v3
        with:
          path: raylib
          repository: raysan5/raylib
      - name: Update config.h
        run: cd ./raylib/src && sed -i 's/#define AUDIO_DEVICE_SAMPLE_RATE           0/#define AUDIO_DEVICE_SAMPLE_RATE           48000/g' config.h
      - name: Intall emsdk
        uses: mymindstorm/setup-emsdk@v11
      - name: Build Raylib WASM
        run: cd ./raylib/src && PLATFORM=PLATFORM_WEB make all
      - name: Gather the files
        run: |
          mkdir -p $GITHUB_WORKSPACE/publish
          mkdir -p $GITHUB_WORKSPACE/staging
          mv raylib/src/libraylib.a $GITHUB_WORKSPACE/staging/ 
          mv raylib/src/raylib.h $GITHUB_WORKSPACE/staging/
          cd $GITHUB_WORKSPACE/staging 
          tar -czf ../publish/raylib.wasm.tar.gz libraylib.a raylib.h
        shell: bash
      - name: Send to publish branch
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: publish
          FOLDER: publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
